services:
    frontend:
      container_name: nuxt-frontend
      build:
        context: ./devops/docker/frontend/
      ports: 
        - "80:3000"
      volumes:
        - ./frontend:/var/www/frontend
        - frontend_volume:/var/www/frontend/node_modules
      tty: true
    # backend:
    #   container_name: node-backend
    #   build:
    #     context: ./docker/backend
    #   environment:
    #     - NODE_ENV=development
    #     - ROOT=/home/node/app
    #   volumes:
    #     - ./backend:/home/node/app/
    #     - backend_volume:/home/node/app/node_modules
    #   ports:
    #     - "3000:3000"
volumes:
  # backend_volume: ~
  frontend_volume: ~