FROM node:lts-buster

WORKDIR /var/www/frontend

COPY ./package.json .

RUN npm install

RUN mkdir -p ./node_modules/ && chmod -R 777 ./node_modules/

EXPOSE 80

USER node

CMD ["npm", "run", "dev"]
